### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by AusiMods** [abedputra/GigaCMS#1]
The captcha image is broken with a few errors after default install by directions
```
Undefined index: _CAPTCHA 
getimagesize(): Filename cannot be empty
imagecreatefrompng(): Filename cannot be empty
imagealphablending() expects parameter 1 to be resource
imagesavealpha() expects parameter 1 to be resource,
imagecolorallocate() expects parameter 1 to be resource
Uncaught exception 'Exception' with message 'Font file not found: '
Font file not found
```
All related to "lib\captcha\captcha.php" 
The image "default.png" is there as is the "times_new_yorker.ttf" font file so i'm guessing its an internal paths problem.

**Comment by abedputra** [comment]
Hai,
`Font file not found`
make sure the font file still there.

**Comment by AusiMods** [comment]
hi.. 
the first error indicates that the script does not recognize _CAPTCHA followed by no file name sent to get image size. Its your design so you are best to understand your own script however i did say the related files are most definitely there . 
![clipboard-1](https://user-images.githubusercontent.com/5730097/28460390-3789f31c-6e55-11e7-8bcc-2cc1af47ff8a.jpg)

never the less thank you for responding.

**Comment by abedputra** [comment]
Hai ausimods,
Thanks for report.
But, I am testing the code on my computer... it's still working, it's fine.
Please check the destination folder of font inside captcha.php, for generate the captcha, or please send all data gigacms to me via email abedputra@gmail.com
Thanks.

**Comment by AusiMods** [comment]
Hi,
I re-downloaded the script and reinstalled this morning from current files available here.
i then installed going strictly by the instructions no alterations to anything but the form inputs as asked.
once installed complete script is working as can be seen from any available links. 
(Note here: it would be nice if when the user is not logged in a register / login link was available in place of the dashboard one.)
Anyways its all working fine but with captcha enabled manually go to register.php and the captcha image is shown as a missing image.
![rgister](https://user-images.githubusercontent.com/5730097/28482927-1078f940-6eae-11e7-86fe-37915de2b592.jpg)

Right clicking on the image to open in new tab shows the errors. 
The errors may be caused by the opening of captcha.php as new tab however it does not alter the fact of the missing captcha image.
So since i have new download i assume to be running same files as you (ie: current). For you to have the same install is as easy as download dont change just install as per own instructions. No point me sending anything when you can as easily create the same.

As long as your sure its working then be happy, i play with/debug random scripts all the time so my server is basically a standard windows server the script was installed one level above www (test/giga/...)
I was looking at your script found a problem and simply reported it. for your benefit only as it was a shame to find a script that installed so well only to have a basic problem make it unusable. It is normally a nightmare to install random scripts and then have problems everywhere it was a refreshing change for me. 

Ok so i wish you the best with your script in the future.  Regards AusiMods
